[versions]
kotlin     = "2.0.21"
coroutines = "1.9.0-RC"
json       = "1.7.3"
ktor       = "3.0.1"
cache4k    = "0.13.0"

[libraries]
coroutines      = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core"   , version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test"   , version.ref = "coroutines" }
json            = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "json" }
cache4k         = { module = "io.github.reactivecircus.cache4k:cache4k"        , version.ref = "cache4k" }

ktor-cio           = { module = "io.ktor:ktor-client-cio"                , version.ref = "ktor" }
ktor-core          = { module = "io.ktor:ktor-client-core-jvm"           , version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-negotiation   = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }

[plugins]
kotlin-jvm           = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }